# Generated by Django 4.2 on 2023-04-24 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsThumbnill',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_thumbnill', to='home.news')),
            ],
            options={
                'ordering': ['uid'],
                'abstract': False,
            },
        ),
    ]
