# Generated by Django 4.2 on 2023-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='newselement',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='newshashtag',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='newsthumbnill',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
