# Generated by Django 4.2 on 2023-04-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_options_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_element', to='home.news'),
        ),
        migrations.DeleteModel(
            name='NewsElement',
        ),
    ]
